const ironMemberInfo = 
[
  {
      "camp": "iOS",
      "name": "Jimmy",
      "account": "jinny1993820",
      "avatar": "https://member.ithome.com.tw/avatars/150548?s=ithelp",
      "subject": "想知道自己iOS具現化系能力有多強嗎？實作幾個App就知道了",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20129144/ironman/3049",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249714",
      "lastArticleSubject": "Day20-在同一個頁面顯示不同UICollectionView之同時顯示兩個CollectionView",
      "lastFinishedDatetime": "10/6/2020, 10:05:06 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "iOS",
      "name": "Alvin",
      "account": "huey_tseing",
      "avatar": "https://member.ithome.com.tw/avatars/131547?s=ithelp",
      "subject": "打造專案管理 iOS App ",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20111538/ironman/3503",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249688",
      "lastArticleSubject": "安能取熊掌而捨魚 SnapKit 進階用法(重做約束)",
      "lastFinishedDatetime": "10/6/2020, 8:35:10 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "iOS",
      "name": "游諭",
      "account": "ytyubox",
      "avatar": "https://member.ithome.com.tw/avatars/140733?s=ithelp",
      "subject": "30 天從 Swift 學會 Objective-C",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20119945/ironman/3242",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249715",
      "lastArticleSubject": "[21] 30 天從 Swift 學會 Objective-C：Swift friendly 的目的是什麼 (auto interface)",
      "lastFinishedDatetime": "10/6/2020, 9:54:22 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "Android",
      "name": "WangWang",
      "account": "WangWang",
      "avatar": "https://member.ithome.com.tw/avatars/142240?s=ithelp",
      "subject": "Android Kotlin開發 -小嫩雞的30篇精選筆記",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20121401/ironman/3579",
      "topicCount": 20,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249247",
      "lastArticleSubject": "Android x Kotlin: 工廠模式淺解",
      "lastFinishedDatetime": "10/5/2020, 10:58:55 AM",
      "hasFinishedToday": false
  },
  {
      "camp": "Android",
      "name": "Kai",
      "account": "kai57",
      "avatar": "https://member.ithome.com.tw/avatars/151145?s=ithelp",
      "subject": "程式初學:Android與Kotlin",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20129700/ironman/3603",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249696",
      "lastArticleSubject": "Day 21--天氣app(七)觀察者模式 Observer Pattern",
      "lastFinishedDatetime": "10/6/2020, 9:08:37 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "Android",
      "name": "宜雯",
      "account": "Elaine5487",
      "avatar": "https://member.ithome.com.tw/avatars/151918?s=ithelp",
      "subject": "Android 菜鳥村-開發基礎 30篇",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20130434/ironman/3620",
      "topicCount": 23,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249729",
      "lastArticleSubject": "[Day 21]  Android Toolbar",
      "lastFinishedDatetime": "10/6/2020, 10:24:55 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "Backend",
      "name": "亮宇",
      "account": "moblinfish",
      "avatar": "https://member.ithome.com.tw/avatars/150994?s=ithelp",
      "subject": "網頁後端的30件小事",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20129556/ironman/3154",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249644",
      "lastArticleSubject": "Laravel：Collection常用的一些方法整理",
      "lastFinishedDatetime": "10/6/2020, 12:38:40 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "Backend",
      "name": "Gill",
      "account": "ishida624",
      "avatar": "https://member.ithome.com.tw/avatars/150832?s=ithelp",
      "subject": "後端新手 使用laravel 從零開始 到開出api",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20129402/ironman/3156",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249735",
      "lastArticleSubject": "Day21 laravel 製作使用者登入api 註冊篇",
      "lastFinishedDatetime": "10/6/2020, 10:38:06 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "Backend",
      "name": "Jhao",
      "account": "jhao",
      "avatar": "https://member.ithome.com.tw/avatars/151035?s=ithelp",
      "subject": "30天完成家庭任務平台",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20129592/ironman/3178",
      "topicCount": 20,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249331",
      "lastArticleSubject": "30天完成家庭任務平台：第二十天",
      "lastFinishedDatetime": "10/5/2020, 5:54:44 PM",
      "hasFinishedToday": false
  },
  {
      "camp": "Backend",
      "name": "Jeff",
      "account": "jeff14884",
      "avatar": "https://member.ithome.com.tw/avatars/136882?s=ithelp",
      "subject": "逆向工程 – 從入門到放棄",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20117397/ironman/3619",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249726",
      "lastArticleSubject": "Day21 - 逆向並找出函式呼叫的特徵",
      "lastFinishedDatetime": "10/6/2020, 10:12:42 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "Backend",
      "name": "Kidd",
      "account": "kiddchan",
      "avatar": "https://member.ithome.com.tw/avatars/146328?s=ithelp",
      "subject": "30天開發與部署 Laravel 專案",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20125263/ironman/3427",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249656",
      "lastArticleSubject": "File Storage：圖片上傳功能",
      "lastFinishedDatetime": "10/6/2020, 10:04:54 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "Web",
      "name": "Penghua",
      "account": "Penghua",
      "avatar": "https://member.ithome.com.tw/avatars/140892?s=ithelp",
      "subject": "與 React 交朋友的三十天學習之旅",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20120099/ironman/3589",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249724",
      "lastArticleSubject": "React Router 與 hooks",
      "lastFinishedDatetime": "10/6/2020, 10:07:15 AM",
      "hasFinishedToday": true
  },
  {
      "camp": "Web",
      "name": "Cathy",
      "account": "shenzhu",
      "avatar": "https://member.ithome.com.tw/avatars/145705?s=ithelp",
      "subject": "網頁阿尼尛，到底是在幹尛？",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20124677/ironman/3583",
      "topicCount": 20,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249309",
      "lastArticleSubject": "第十九章、你好啊鐵人們，接下來就由我鎖鏈 Canvas 對付你！(其三)",
      "lastFinishedDatetime": "10/5/2020, 2:38:52 PM",
      "hasFinishedToday": false
  },
  {
      "camp": "Web",
      "name": "Titangene",
      "account": "titangene",
      "avatar": "https://member.ithome.com.tw/avatars/138209?s=ithelp",
      "subject": "JavaScript 之旅",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20117586/ironman/3607",
      "topicCount": 20,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249382",
      "lastArticleSubject": "JavaScript 之旅 (20)：Promise.allSettled()",
      "lastFinishedDatetime": "10/5/2020, 5:58:54 PM",
      "hasFinishedToday": false
  },
  {
      "camp": "Web",
      "name": "Chris",
      "account": "chris47",
      "avatar": "https://member.ithome.com.tw/avatars/126913?s=ithelp",
      "subject": "完美 Camp 進化論",
      "ironmanUrl": "https://ithelp.ithome.com.tw/users/20107637/ironman/3641",
      "topicCount": 21,
      "lastArticleLink": "https://ithelp.ithome.com.tw/articles/10249737",
      "lastArticleSubject": "團體的強與弱？如何產生強的團隊？",
      "lastFinishedDatetime": "10/6/2020, 10:41:32 AM",
      "hasFinishedToday": true
  }
]

export {ironMemberInfo}